### ISSUE TITLE
Problem: The result is not unique

### ISSUE THREAD

**Issue by blossom-v** [alirezadavoudi/DPLM#1]
Hi,

I am using your toolbox for dimensionality reduction of SPD matrices. And I use the method of FGMDM classification for two-class Motor Imagery BCI. I use the datasetⅠ from the BCI competition IV. The time interval is restricted to the time segment comprised between 0.5 and 2.5s.  

However, the result I calculated is not unique (When I run it every time, the value of U is different). Do you know where the problem is? I hope to get your reply as soon as possible.

Thank you

**Comment by adavoudi** [comment]
Hi,

It is because every time you run the algorithm, the optimizer starts from a random point. You can set your random generator's seed to a fixed number to always start from the same starting point.

**Comment by blossom-v** [comment]
Sorry for the late answer. Thank you for answering my question. I will modify the program and test it. Thanks again.
